### ISSUE TITLE
problems accessing expo srx from noc/zabbix

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#241] opened 2019-03-10 21:10 UTC
could ping via ipv4, but snmp did not work

**Comment by owendelong** [comment] 2019-09-06 01:10
I have some suspicions and I have the SRXs here... Need to set them up in a lab-environment and duplicate the issue, then test further.

**Comment by owendelong** [comment] 2020-02-15 03:00
Yeah, IPv4 SNMP isn't expected to work... IPv6 is configured...

CF-MDF: 
set snmp community <redacted> clients 2001:470:f325:103::/64
set snmp community <redacted> clients 2001:470:f325:503::/64

EX-MDF:
set snmp community <redacted> clients 2001:470:f325:103::/64
set snmp community <redacted> clients 2001:470:f325:503::/64

BR-MDF:
set snmp community <redacted> clients 2001:470:f325:103::/64
set snmp community <redacted> clients 2001:470:f325:503::/64

Is there some reason we need IPv4 SNMP?

**Comment by sbibayoff** [comment] 2020-02-24 22:54
Zabbix could/does snmp and monitoring through zabbix agents through IPv6. Will initially set it up to ONLY do IPv6 to see how that behaves.

I'm keeping this issue open till we verify.

**Comment by owendelong** [comment] 2020-02-25 00:38
Closing this one out as "works as intended".

**Closed by owendelong** 2020-02-25 00:38 UTC
Labels: Scale 18x prep
